FROM ubuntu:22.04
RUN apt-get update && \
    apt-get -y install gcc && apt-get -y install g++
# libpq5 libpq-dev libpqxx-dev
COPY teste_docker.cpp teste_docker.cpp
RUN g++ -o teste_docker teste_docker.cpp
CMD ["./teste_docker"]
